### ISSUE TITLE
how to set figsize

### ISSUE THREAD

**Issue by bsb2014** [mortazavilab/PyWGCNA#100]
I want to set the figsize in the function module_trait_relationships_heatmap. However, I do not know what format the option can accept. Could you please give me an example (such as Figsize=20*20 )? 

The plotting is not proper if few traits only. The font size of p-values and coefficient is oversized.

Can I save the Network to png/pdf rather than html?

Thanks.

**Comment by bsb2014** [comment]
![image](https://github.com/mortazavilab/PyWGCNA/assets/73562686/6ffd742c-0779-4b31-8944-7c4c9fc36464)

**Comment by nargesr** [comment]
Hi,

Please look at the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=module_trait_relationships#PyWGCNA.wgcna.WGCNA.module_trait_relationships_heatmap) regarding the format of figsize. 

```
module_trait_relationships_heatmap(metaData, alternative='two-sided', figsize=None, show=True, file_name='module-traitRelationships')
figsize (tuple of float) – indicates the size of the plot (20, 20)
```

about your second question, since the network plot is an interactive plot, we couldn’t save it as PNG or pdf but I'm pretty sure you can convert it easily afterwards.

Best,
Narges
