### ISSUE TITLE
I can't follow the tutorial

### ISSUE THREAD

**Issue by alberto-mora** [mortazavilab/PyWGCNA#14]
I am following the tutorial but at this point:
pyWGCNA_5xFAD = PyWGCNA.WGCNA(name='5xFAD', species='mouse',
                              geneExpPath=geneExp, 
                              save=True)
I get this error: 
ValueError: no types given
As I am using the data provided for the tutorial I do not know what might be wrong
Thanks in advance

**Comment by nargesr** [comment]
Hi,

I updated [5xFAD_paper.zip](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/5xFAD_paper.zip). Please download the updated version and let me know if you still have that problem.
thank you so much

**Comment by alberto-mora** [comment]
It worked. Thank you so much!
Now im using my own data but the expression values are in FPKM.
Would it make any difference to the analysis?

**Comment by nargesr** [comment]
When you use TPM, the sum of all TPMs in each sample is the same. This makes it easier to compare the proportion of reads that mapped to a gene in each sample. In contrast, with FPKM, the sum of the normalized reads in each sample may be different, and this makes it harder to compare samples directly.

Overall, I would suggest using TPM if you have that information otherwise you can use FPKM but you might get an artificial class due to you're using FPKM...
