### ISSUE TITLE
barplotModuleEigenGene

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#34]
Hi,
The following is a figure generated by barplotModuleEigenGene, could you explain the meanings of the bar height/the grey points/ the red points and the red vertical lines ?
![output](https://user-images.githubusercontent.com/29703450/232990459-da591cea-5e2b-4a3c-a70b-a5cd0e31000d.png)
![下载](https://user-images.githubusercontent.com/29703450/232990880-d579ba29-9b5b-4a86-afd2-667e636e4737.png)
Besides, I have found a flaw of barplotModuleEigenGene, for example, when there are only a few traits, the figure cannot be show properly, the title is very large and the bars disappears !
![image](https://user-images.githubusercontent.com/29703450/232991764-aafb64a6-20ef-42ca-beef-70e7fc90fc93.png)

Hope you are kind enough to fix it.

**Comment by nargesr** [comment]
Hi,

each dot shows the eigengene values of the genes in each module for each sample. instead of showing one bar plot for each sample like [this](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/figures/module_heatmap_eigengene_indianred.pdf), you can aggregate them base on one of the categories you have in your data set. which in this case we show all the value for each genotype in each time/sex/tissue and then color each bar base on the categories.

If you can send me an example of your pickle file, I can try to fix it

**Comment by wangjiawen2013** [comment]
I'll send you the pickle if you can leaving your email. Or you can keep only "Age" in pyWGCNA 5xFAD object, then run analyseWGCNA(), perhaps you'll find that the heatmap looks crowded and the barplots also looks weird, the bar disappers.

**Comment by nargesr** [comment]
my email is nargesr@uci.edu

**Comment by nargesr** [comment]
For me, the bar plots look fine on the pickle file you sent me!
I attached two versions one with age as an annotation and the other one with age indicating the color of the bars
![image](https://user-images.githubusercontent.com/57965133/234377110-7009565e-de8c-4ef9-81f7-07997abc36fb.png)
![image](https://user-images.githubusercontent.com/57965133/234377172-4474b9cd-1eed-45b6-a1a4-59379f31f19f.png)

**Comment by wangjiawen2013** [comment]
Yes, you're right. I run it again and now everything is OK. I'll try to find what caused the weird figures before. Perhaps I set the wong matplotlib and seaborn parameters in my vscode.
