### ISSUE TITLE
module-traitRelationships negative correlation p values incorrect

### ISSUE THREAD

**Issue by richard-k-perez** [mortazavilab/PyWGCNA#73]
Hello,

There is an issue with p value calculation for negative correlations in the module-trait relationship. For example, if I calculate the correlation A vs. B, the results are R=0.7 p <0.01. When I use the same data but now make the trait B vs. A, the results are R =-0.7 p = 0.99. The p-value is always 1-p of the opposite comparison. I tested this myself by extracting the eigenvalues for each of my samples for a module and switched the order of comparison. I reproduced the correlation for both comparisons but only the p value for the correlation. The p value for the negative correlation in my test, was as significant as the positive correlation, which is to be expected.

Hoping you could look into this! May be a very quick fix.

**Comment by nargesr** [comment]
Hi,

Thanks for using PyWGCNA, would you mind telling me the approach you used?

On my side, I used [scipy.stats.pearsonr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html) with alternative='greater', so I would assume your observation it because you probably go with the alternative='two-sided'.

I'm happy to change the alternative parameter if that's the problem here

**Comment by richard-k-perez** [comment]
Hello,

Ah I think that’s the issue! Yeah I used the default for the Pearson r
test, which happens to be the two sided. I can check later tonight or
tomorrow if I can recreate the issue but I think it’s like you said. Could
you change the alternative parameter to two-sided or make it an option?

Thanks,
Richard

**Comment by nargesr** [comment]
Hi @richard-k-perez 

sure happy to change it and make it an option in the next release.

Will close this issue once I make a new release.
