### ISSUE TITLE
ask for some questions

### ISSUE THREAD

**Issue by chulexuexibiedebushihewo** [mortazavilab/PyWGCNA#83]
![Uploading image.png…]()
Hi! May I ask you for a question? 
When I run following code, "pyWGCNA_5xFAD.findModules()", to determine the number of blocks, the number of blocks is equal to the number of genes. I feel there may be existing some strange things, such as gene names is wrong caused this situation.

**Comment by nargesr** [comment]
Hi, I couldn’t see your image. 
would you mind also sending me a snapshot of your input data?

**Comment by nargesr** [comment]
Hi, If you have the latest version of pyWGCNA, I wouldn’t be worried about it. Since you don’t have too many genes in your input data the block size would be your whole data. For example, that is not the case for [Quick Start](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/Quick_Start.ipynb).

please feel free to reopen this issue if you have any questions
